import { Button, VerticalBox, TextEdit, HorizontalBox, ScrollView } from "std-widgets.slint";

struct Perception {
    lin_speed: [float],
    rot_speed: [float],
    location: [float],
    current_alt: float,
    roll: float,
    pitch: float,
    yaw: float,
}

struct DisplaySize {
    width: int,
    height: int,
}

export component OsprAiWindow inherits Window {
    in-out property <string> connection_msg: "TEST";
    in-out property <string> arm_msg: "Arm\nDrone";
    in-out property <float> altitude: 0.0;
    in-out property <[float]> location: [0.0, 0.0];
    in-out property <[float]> lin_speed: [0.0, 0.0, 0.0];
    in-out property <[float]> rot_speed: [0.0, 0.0, 0.0];
    in-out property <[float]> orientation: [0.0, 0.0, 0.0];
    in property <image> cam_display;
    in property <image> monitoring_display;
    in-out property <DisplaySize> cam_display_size: { 
        width: cam_display.width / 1px,
        height: cam_display.height / 1px,
    };
    in-out property <DisplaySize> monitoring_display_size: { 
        width: monitoring_display.width / 1px,
        height: monitoring_display.height / 1px,
    };
    callback arm_drone();
    callback disarm_drone();
    callback start_logs_record();
    callback stop_logs_record();
    callback send_setpoint();
    pure callback render_plot();
    
    width: 1900px;
    always-on-top: false;
    height: 1040px;
    title: "OsprAi";
    VerticalLayout {
        HorizontalLayout {
            height: parent.height - 20px;
            VerticalLayout {
                width: 6/10.0 * parent.width;
                height: parent.height;
                cam_display := Image {
                    source: root.cam_display;
                    horizontal-alignment: left;
                    vertical-alignment: top;
                }
                monitoring_display := Image {
                    source: root.monitoring_display;
                    horizontal-alignment: left;
                    vertical-alignment: bottom;
                }
            }
            
            VerticalLayout {
                width: 4/10.0 * parent.width;
                vertical-stretch: 1;
                ScrollView {
                    height: parent.height /2.0;
                    TextEdit {
                        enabled: false;
                        height: parent.height; 
                        width: parent.width;
                        placeholder-text: "  Drone Logs";
                    }
                }
                HorizontalLayout {
                    padding-bottom: 10px;
                    padding-top: 10px;
                    VerticalLayout {
                        padding-bottom: 10px;
                        padding-top: 10px;
                        Text {
                            min-height: 30px;
                            max-height: 40px;
                            text: "Current GPS Location";
                            horizontal-alignment: center;
                            font-weight: 800;                    
                        }
                        HorizontalLayout {
                            spacing: 8px;
                            padding-top: 10px;
                            padding-bottom: 10px;
                            min-height: 30px;
                            max-height: 40px;
                            Text {
                                text: location[0].to-precision(10);
                                horizontal-alignment: center;
                                vertical-alignment: top;
                                
                            }
                            Text {
                                text: location[1].to-precision(10);
                                horizontal-alignment: center;
                                vertical-alignment: top;
                                
                            }
                        }
                    }
                    VerticalLayout {
                        padding-bottom: 10px;
                        padding-top: 10px;
                        Text {
                            min-height: 30px;
                            max-height: 40px;
                            text: "Altitude ";
                            horizontal-alignment: center;
                            font-weight: 800;                    
                        }
                        HorizontalLayout {
                            spacing: 8px;
                            padding-top: 10px;
                            padding-bottom: 10px;
                            min-height: 30px;
                            max-height: 40px;
                            Text {
                                text: altitude.to-precision(7);
                                horizontal-alignment: center;
                                vertical-alignment: top;
                                
                            }
                        }
                    }
                }
                VerticalLayout {
                    padding-bottom: 10px;
                    padding-top: 10px;
                    Text {
                        min-height: 30px;
                        max-height: 40px;
                        text: "Current Orientation:";
                        horizontal-alignment: center;
                        font-weight: 800;
                        
                    }
                    HorizontalLayout {
                        spacing: 8px;
                        padding-top: 10px;
                        padding-bottom: 10px;
                        min-height: 30px;

                        // Reserve enough width to fit the largest expected text,
                        // include minus sign, digits, decimal point, etc.
                        // Adjust 120px or so depending on how many characters your precision uses.

                        Text {
                            horizontal-alignment: center;
                            vertical-alignment: top;
                            // Pad positive values with a space
                            text: (orientation[0] < 0 ? "" : " ") + orientation[0].to-fixed(2);
                        }
                        Text {
                            horizontal-alignment: center;
                            vertical-alignment: top;
                            text: (orientation[1] < 0 ? "" : " ") + orientation[1].to-fixed(2);
                        }
                        Text {
                            horizontal-alignment: center;
                            vertical-alignment: top;
                            text: (orientation[2] < 0 ? "" : " ") + orientation[2].to-fixed(2);
                        }
                    }
                }
                HorizontalLayout {
                    Button {
                        max-height: 40px;
                        min-height: 40px;
                        width: 1/3.0 * parent.width;
                        text: arm_msg;
                        clicked => {
                            if (arm_msg == "Arm\nDrone") {
                                arm_drone();
                            } else {
                                disarm_drone();
                            }
                        }
                    }
                    Button {
                        max-height: 70px;
                        min-height: 30px;
                        width: 1/3.0 * parent.width;
                        text: "Start \nLogs Record";
                        clicked => {
                            start_logs_record();
                        }
                    }
                    Button {
                        max-height: 70px;
                        min-height: 30px;
                        width: 1/3.0 * parent.width;
                        text: "Stop \nLogs Record";
                        clicked => {
                            stop_logs_record();
                        }
                    }
                }
            }
        }
        HorizontalLayout {
            padding-right: 10px;
            padding-top: 5px;
            Text {
                text: connection_msg;
                font-size: 10px;
                font-weight: 300;
                horizontal-alignment: right;
            }
        }
    }
    
}