[package]
name = "Controller"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = "1.6.0"
tokio = { version = "1", features = ["full"] }
plotters = "0.3"

[build-dependencies]
slint-build = "1.5.0"
